### ISSUE TITLE
Project homepage says "this recording has been archived" at the bottom for the asciinema thing

### ISSUE THREAD

**Issue by josephrocca** [neon-bindings/website#84] opened 2019-05-18 15:19 UTC
The project homepage says "this recording has been archived" at the bottom for the asciinema thing.

**Comment by jeffvandyke** [comment] 2019-06-11 17:41
Still does

**Comment by amilajack** [comment] 2019-08-19 17:46
Duplicate of https://github.com/neon-bindings/website/issues/84

**Closed by amilajack** 2019-08-19 17:46 UTC

**Comment by jeffvandyke** [comment] 2019-08-19 18:57
Uhh, what? The message says "Duplicate of #84", but this *is* issue 84... issue #408 is also marked as a duplicate of #84... something wierd's going on.

Also, the issue is still unfixed.
