### ISSUE TITLE
"This recording has been archived"

### ISSUE THREAD

**Issue by isiahmeadows** [neon-bindings/website#76] opened 2019-02-11 05:30 UTC
When looking on the main site, the link to the demo shows this:

![screen shot 2019-02-11 at 12 31 23 am](https://user-images.githubusercontent.com/4483844/52547215-0d1e2580-2d94-11e9-8e7d-5b34d928eb2c.png)

And when [clicking the link](https://asciinema.org/a/ZXrZmY5ofORmdlKKrm8ev0QC7), it shows a page that reads "All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload."

**Comment by amilajack** [comment] 2019-02-12 03:05
This is a duplicate of https://github.com/neon-bindings/website/issues/75

**Closed by amilajack** 2019-02-12 03:05 UTC
